site_name: CS Wiki

site_url: https://mingsm17518.github.io/cs-wiki/
site_author: mingsm17518

nav: 
  - 主页: 
    - 主页: index.md
    - Home: Home.md
  - 关于: 
    - about: 关于/about.md
    - 随笔: 关于/消极自由.md
    - 书摘: 关于/《我的外婆从不内耗》.md
  - 静态网页的搭建: mkdocs.md
  - test: test.md
  - others: 
    - Ubuntu扩展内存: Ubuntu扩展内存.md
    - 激活Typora: 激活Typora.md
  - c++: 
    - C++基础入门: c++/C++基础入门.md
    - 通讯录管理系统: c++/通讯录管理系统.md
    - C++核心编程: c++/C++核心编程.md
    - 职工管理系统: c++/职工管理系统.md
    - C++提高编程: c++/C++提高编程.md
  - c:
    - C语言入门: c/初识C语言.md

# mkdocs.yaml
extra_javascript:
    - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'

# plugins:
#   - search
#   - pdf-export

theme:
  custom_dir: custom_dir/
  name: "material"
  # logo:
  #     icon: ""
  # palette:
  #     primary: "black"
  #     accent: "white"
  language: "zh"
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - content.action.edit
  palette:
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: white
        accent: red
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        accent: red
        toggle:
          icon: material/weather-night
          name: Switch to light mode
  # favicon: 'favicon.ico'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - pymdownx.snippets
  - attr_list
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - meta
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - footnotes
  - pymdownx.critic
  - admonition
  - md_in_html
  - codehilite:
      guess_lang: false
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.betterem:
      smart_enable: 'underscore'
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra: 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mingsm17518/cs-wiki
    
repo_name: cs-wiki
repo_url: https://github.com/mingsm17518/cs-wiki
