site_name: CS-Wiki

theme:
  custom_dir: custom_dir/
  name: "material"
  # logo:
  #     icon: ""
  palette:
      primary: "black"
      accent: "white"
  language: "zh"



nav: 
  - 主页: index.md
  - 关于: about.md
  - mkdocs: mkdocs.md
  - test: test.md